<?php

class Data
{
    // This will provide the data you need
    // No need to change any logic here - only data (to add or update words)
    public static function words(): array
    {
        return [
            'adventure' => 'avontuur',
            'celebrate' => 'vieren',
            'decision' => 'beslissing',
            'elephant' => 'olifant',
            'family' => 'familie',
            'gorgeous' => 'prachtig',
            'harmony' => 'harmonie',
            'identity' => 'identiteit',
            'journey' => 'reis',
            'knowledge' => 'kennis',
            'language' => 'taal',
            'magnificent' => 'magnifiek',
            'narrative' => 'verhaal',
            'operation' => 'operatie',
            'pleasant' => 'aangenaam',
            'quantity' => 'hoeveelheid',
            'reliable' => 'betrouwbaar',
            'symphony' => 'symfonie',
            'tranquil' => 'rustig',
            'unique' => 'uniek',
            'victory' => 'overwinning',
            'wonderful' => 'schitterend',
            'bamboo' => 'bamboe',
            'capture' => 'vangen',
            'delicious' => 'heerlijk',
            'enormous' => 'enorm',
            'fantastic' => 'fantastisch',
            'gesture' => 'gebaar',
            'melody' => 'melodie',
            'infinite' => 'oneindig',
            'jovial' => 'gezellig',
            'kilometer' => 'kilometer',
            'lavender' => 'lavendel',
            'majestic' => 'majestueus',
            'nostalgia' => 'nostalgie',
            'opportunity' => 'gelegenheid',
            'passion' => 'passie',
            'quotation' => 'citaat',
            'radiant' => 'stralend',
            'spectrum' => 'spectrum',
            'tantalize' => 'verleiden',
            'unanimous' => 'eensgezind',
            'venture' => 'onderneming',
            'wisdom' => 'wijsheid',
            'xenophobia' => 'xenofobie',
            'youthful' => 'jeugdig',
            'zeppelin' => 'zeppelin',
            'accurate' => 'nauwkeurig',
            'breathe' => 'ademen',
            'cascade' => 'waterval',
            'dazzling' => 'verblindend',
            'eccentric' => 'excentriek',
            'fluctuate' => 'fluctueren',
            'glorious' => 'glorieus',
            'hypnotize' => 'hypnotiseren',
            'illuminate' => 'verlichten',
            'juxtapose' => 'juxtaposeren',
            'kaleidoscope' => 'kaleidoscoop',
            'labyrinth' => 'doolhof',
            'melancholy' => 'melancholie',
            'nebula' => 'nevel',
            'oasis' => 'oase',
            'pinnacle' => 'top',
            'visionary' => 'visionair',
            'resilient' => 'veerkrachtig',
            'serenade' => 'serenade',
            'tranquility' => 'rust',
            'umbrella' => 'paraplu',
            'vibrant' => 'levendig',
            'whimsical' => 'grillig',
            'odyssey' => 'odyssee',
            'longing' => 'verlangen',
            'breeze' => 'bries',
            'blissful' => 'zalig',
            'chameleon' => 'kameleon',
            'delightful' => 'heerlijk',
            'enchanting' => 'betoverend',
            'frivolous' => 'frivool',
            'glimmer' => 'glinsteren',
            'harmonious' => 'harmonieus',
            'iridescent' => 'iriserend',
            'jubilant' => 'uitbundig',
            'kinetic' => 'kinetisch',
            'luscious' => 'sappig',
            'mellifluous' => 'welluidend',
            'nebulous' => 'vaag',
            'opulent' => 'weelderig',
            'quizzical' => 'raadselachtig',
            'rendezvous' => 'ontmoeting',
            'sumptuous' => 'luxueus',
            'apprehension' => 'bezorgdheid',
            'unabashed' => 'ongeneerd',
            'verdant' => 'groen',
            'winsome' => 'aantrekkelijk',
            'hospitable' => 'gastvrij',
            'zenith' => 'hoogtepunt',
            'ambiance' => 'sfeer',
            'whirlwind' => 'wervelwind',
            'zestful' => 'levendig'
        ];
    }
    
}